export const Users = [
    {
        id: 1,
        profilePicture: "assets/users/1.jpg",
        username: "Jane Doe",
    },
    {
        id: 2,
        profilePicture: "assets/users/2.jpg",
        username: "Rosa Fernandez",
    },
    {
        id: 3,
        profilePicture: "assets/users/3.jpg",
        username: "Kim Swanson",
    },
    {
        id: 4,
        profilePicture: "assets/users/4.jpg",
        username: "Victor Hunt",
    },
    {
        id: 5,
        profilePicture: "assets/users/5.jpg",
        username: "Zachary Davidson",
    },
    {
        id: 6,
        profilePicture: "assets/users/6.jpg",
        username: "Annette Cohen",
    },
    {
        id: 7,
        profilePicture: "assets/users/7.jpg",
        username: "Clifford McCarthy",
    },
    {
        id: 8,
        profilePicture: "assets/users/8.jpg",
        username: "Kay Mason",
    }
];

export const Posts = [
    {
        id: 1,
        desc: "Time is a great teacher, but unfortunately it kills all its pupils.",
        photo: "assets/posts/1.jpg",
        date: "8 mins ago",
        userId: 1,
        like: 56,
        comment: 11,
    },
    {
        id: 2,
        desc: "Never take life seriously. Nobody gets out alive anyway.",
        photo: "assets/posts/2.jpg",
        date: "23 mins ago",
        userId: 2,
        like: 33,
        comment: 24,
    },
    {
        id: 3,
        desc: "Insanity: doing the same thing over and over again and expecting different results.",
        photo: "assets/posts/3.jpg",
        date: "55 mins ago",
        userId: 3,
        like: 45,
        comment: 19,
    },
    {
        id: 4,
        desc: "Men are like steel; both are worthless when they lose their temper.",
        photo: "assets/posts/4.jpg",
        date: "7 hours ago",
        userId: 1,
        like: 19,
        comment: 9,
    },
    {
        id: 5,
        desc: "Don’t use a big word where a diminutive one will suffice.",
        photo: "assets/posts/5.jpg",
        date: "10 hours ago",
        userId: 5,
        like: 26,
        comment: 4,
    },
    {
        id: 6,
        desc: "If you must choose between two evils, pick the one you’ve never tried before.",
        photo: "assets/posts/6.jpg",
        date: "1 day ago",
        userId: 3,
        like: 25,
        comment: 5,
    },
    {
        id: 7,
        desc: "God save me from my friends. I can protect myself from my enemies.",
        photo: "assets/posts/7.jpg",
        date: "1 day ago",
        userId: 2,
        like: 32,
        comment: 3,
    },
    {
        id: 8,
        desc: "When you go in search of honey you must expect to be stung by bees.",
        photo: "assets/posts/8.jpg",
        date: "2 days ago",
        userId: 2,
        like: 78,
        comment: 16,
    },
    {
        id: 9,
        desc: "There is always danger for those who are afraid of it.",
        photo: "assets/posts/9.jpg",
        date: "3 days ago",
        userId: 8,
        like: 66,
        comment: 2,
    },
    {
        id: 10,
        desc: "Nothing is hopeless; we must hope for everything.",
        photo: "assets/posts/10.jpg",
        date: "4 days ago",
        userId: 6,
        like: 59,
        comment: 21,
    }
]